{
 "title": "Booking DevOps Lab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  node_memory_MemAvailable_bytes\r\n  /\r\n  node_memory_MemTotal_bytes\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available App Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{\r\n  namespace=\"booking\",\r\n  deployment=\"booking-app\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Booking App Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\r\n  container_memory_working_set_bytes{\r\n    namespace=\"booking\",\r\n    pod=~\"booking-app-.*\",\r\n    container!=\"POD\",\r\n    image!=\"\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Booking App CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      namespace=\"booking\",\r\n      pod=~\"booking-app-.*\",\r\n      container!=\"POD\",\r\n      image!=\"\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}