{{- if .Values.tls.enabled }}
{{- $email := required "tls.email is required" .Values.tls.email }}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: booking-letsencrypt-staging

spec:
  acme:
    email: {{ $email | quote }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: booking-letsencrypt-staging

    solvers:
      - http01:
          ingress:
            ingressClassName: traefik

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: booking-letsencrypt-prod

spec:
  acme:
    email: {{ $email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: booking-letsencrypt-prod

    solvers:
      - http01:
          ingress:
            ingressClassName: traefik

{{- end }}
