apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
