apiVersion: v1
kind: Service
metadata:
  name: booking-postgres
spec:
  selector:
    app.kubernetes.io/name: booking-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

  type: ClusterIP
